# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be30796e87ced49c321feacfb6593690dcc34f0b642a32f95d1d78360565f35f0575322cab57465026a17232db8c6e6aa8ed14263ab8950a0fd4c087f9b86c3b

test:
  secret_key_base: d9e0a8a0c9f48d84c8f50e198dcc36a207673a7b202b0b2608806e2e8a258546a30487b6fa0a4e06add22d099a0269e55048a74fb3c65744e8bab2b066861086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
